import {mustMember,checkOrigin,all,one,run,bucket,database,now,AccessError} from '../../../../lib/classroom';
import {sessionFor,describe,boundedBytes,uploadError} from '../../../../lib/multipart';
import {PART_SIZE,MAX_FILES,matchesFileType} from '../../../../lib/upload-policy';
export const dynamic='force-dynamic';
type Params={params:Promise<{id:string}>};
export async function GET(req:Request,{params}:Params){try{const m=await mustMember();return Response.json(await describe(await sessionFor((await params).id,m)),{headers:{'Cache-Control':'no-store'}})}catch(e){return uploadError(e)}}
export async function PUT(req:Request,{params}:Params){try{checkOrigin(req);const s=await sessionFor((await params).id,await mustMember());if(s.status!=='open')throw new AccessError('上传任务已结束');const number=Number(new URL(req.url).searchParams.get('part'));const total=Math.ceil(s.size/PART_SIZE);if(!Number.isInteger(number)||number<1||number>total)throw new AccessError('分片编号不正确');const size=Math.min(PART_SIZE,s.size-(number-1)*PART_SIZE);const bytes=await boundedBytes(req,size);if(bytes.length!==size)throw new AccessError('分片不完整，请重试');if(number===1&&!matchesFileType(bytes,s.mime))throw new AccessError('文件内容与类型不一致');const part=await bucket().resumeMultipartUpload('uploads/'+s.id,s.storage_id).uploadPart(number,bytes);await run('INSERT INTO upload_parts(id,session,number,size,etag) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET size=excluded.size,etag=excluded.etag',s.id+':'+number,s.id,number,size,part.etag);return Response.json({ok:true,number,size},{headers:{'Cache-Control':'no-store'}})}catch(e){return uploadError(e)}}
export async function POST(req:Request,{params}:Params){try{checkOrigin(req);const m=await mustMember();const s=await sessionFor((await params).id,m);const existing=await one('SELECT id FROM files WHERE id=?',s.id);if(existing)return Response.json({ok:true,id:s.id});if(s.status!=='open')throw new AccessError('上传任务已结束');const parts=await all<{number:number;size:number;etag:string}>('SELECT number,size,etag FROM upload_parts WHERE session=? ORDER BY number',s.id);const total=Math.ceil(s.size/PART_SIZE);if(parts.length!==total||parts.some((p,i)=>p.number!==i+1||p.size!==Math.min(PART_SIZE,s.size-i*PART_SIZE)))throw new AccessError('文件尚未全部上传，请继续上传',409);
 const count=await one<{count:number}>('SELECT COUNT(*) AS count FROM files WHERE post=?',s.post);if((count?.count||0)>=MAX_FILES)throw new AccessError('每条内容最多60个文件');
 let object=await bucket().head('uploads/'+s.id);if(!object)object=await bucket().resumeMultipartUpload('uploads/'+s.id,s.storage_id).complete(parts.map(p=>({partNumber:p.number,etag:p.etag})));if(object.size!==s.size)throw new AccessError('文件大小校验失败，请重新上传');
 await database().batch([database().prepare('INSERT INTO files(id,post,name,mime,size,position,created) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(s.id,s.post,s.name,s.mime,s.size,count?.count||0,now()),database().prepare('UPDATE upload_sessions SET status=? WHERE id=?').bind('complete',s.id)]);return Response.json({ok:true,id:s.id},{headers:{'Cache-Control':'no-store'}})}catch(e){return uploadError(e)}}
export async function DELETE(req:Request,{params}:Params){try{checkOrigin(req);const s=await sessionFor((await params).id,await mustMember());if(s.status!=='open')throw new AccessError('上传任务已结束');await bucket().resumeMultipartUpload('uploads/'+s.id,s.storage_id).abort();await database().batch([database().prepare('UPDATE upload_sessions SET status=? WHERE id=?').bind('aborted',s.id),database().prepare('DELETE FROM upload_parts WHERE session=?').bind(s.id)]);return Response.json({ok:true})}catch(e){return uploadError(e)}}
