import {all,one,run,id,now,bucket,teacher,AccessError,type Member,type Post} from './classroom';
import {MAX_FILE_SIZE,PART_SIZE,MAX_FILES,MIME_TYPES} from './upload-policy';
export type Session={id:string;owner:string;post:string;name:string;mime:string;size:number;fingerprint:string;storage_id:string;status:string;created:string;expires:string};
export async function uploadPost(postId:string,m:Member){const p=await one<Post>('SELECT * FROM posts WHERE id=?',postId);if(!p||p.deleted||(!teacher(m)&&p.owner!==m.id))throw new AccessError('无权上传到该内容',403);if(!teacher(m)){if(p.status==='published')throw new AccessError('请先保存修改稿，再上传文件');const term=await one<{archived:number}>('SELECT archived FROM terms WHERE id=?',p.term);if(term?.archived)throw new AccessError('历史学期已归档，不能继续上传');}return p;}
export async function sessionFor(sessionId:string,m:Member){const s=await one<Session>('SELECT * FROM upload_sessions WHERE id=?',sessionId);if(!s||s.owner!==m.id)throw new AccessError('上传任务不存在或不属于你',403);await uploadPost(s.post,m);if(s.expires<now()&&s.status!=='complete')throw new AccessError('上传任务已过期，请重新上传',410);return s;}
export async function describe(s:Session){return {id:s.id,partSize:PART_SIZE,size:s.size,status:s.status,parts:(await all<{number:number;size:number}>('SELECT number,size FROM upload_parts WHERE session=? ORDER BY number',s.id)).map(p=>({number:p.number,size:p.size}))};}
export async function beginUpload(b:Record<string,any>,m:Member){await uploadPost(String(b.post),m);const size=Number(b.size),mime=String(b.mime),name=String(b.name||'').trim().slice(0,200),fingerprint=String(b.fingerprint||'');if(!Number.isSafeInteger(size)||size<1||size>MAX_FILE_SIZE)throw new AccessError('每个文件最大1GB（1024MB）');if(!MIME_TYPES.includes(mime)||!name)throw new AccessError('支持 JPG、PNG、WebP、MP4、WebM 和 PDF');if(!/^[a-f0-9]{64}$/.test(fingerprint))throw new AccessError('文件校验标识不正确');
 const prior=await one<Session>('SELECT * FROM upload_sessions WHERE owner=? AND post=? AND fingerprint=? AND size=? AND mime=? AND name=? AND status IN (?,?) AND expires>? ORDER BY created DESC LIMIT 1',m.id,b.post,fingerprint,size,mime,name,'open','complete',now());if(prior)return describe(prior);
 const count=await one<{count:number}>('SELECT (SELECT COUNT(*) FROM files WHERE post=?)+(SELECT COUNT(*) FROM upload_sessions WHERE post=? AND status=? AND expires>?) AS count',b.post,b.post,'open',now());if((count?.count||0)>=MAX_FILES)throw new AccessError('每条内容最多60个文件（包括上传中的文件）');
 const sid=id(),storage=await bucket().createMultipartUpload('uploads/'+sid,{httpMetadata:{contentType:mime}});const created=now(),expires=new Date(Date.now()+24*3600000).toISOString();try{await run('INSERT INTO upload_sessions(id,owner,post,name,mime,size,fingerprint,storage_id,status,created,expires) VALUES(?,?,?,?,?,?,?,?,?,?,?)',sid,m.id,b.post,name,mime,size,fingerprint,storage.uploadId,'open',created,expires);}catch(e){await storage.abort();throw e;}return describe({id:sid,owner:m.id,post:b.post,name,mime,size,fingerprint,storage_id:storage.uploadId,status:'open',created,expires});}
export async function boundedBytes(req:Request,limit:number){if(Number(req.headers.get('content-length')||0)>limit)throw new AccessError('分片超过大小限制',413);if(!req.body)throw new AccessError('分片内容为空');const reader=req.body.getReader();let size=0;const chunks:Uint8Array[]=[];try{for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>limit){await reader.cancel();throw new AccessError('分片超过大小限制',413);}chunks.push(value);}}finally{reader.releaseLock();}const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length;}return bytes;}
export function uploadError(e:unknown){console.error('multipart upload',e);return Response.json({error:e instanceof AccessError?e.message:'上传服务暂时不可用，请重试；已完成的分片会保留。'},{status:e instanceof AccessError?e.status:503,headers:{'Cache-Control':'no-store'}});}
