// Intentionally empty by default.
// Add Drizzle tables here when the site actually needs a database.
// See examples/d1/db/schema.ts for an opt-in example.
import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';
export const members = sqliteTable('members', {id:text('id').primaryKey(), email:text('email').notNull(), name:text('name').notNull(), role:text('role').notNull(), students:text('students').notNull().default('[]')});
export const students = sqliteTable('students', {id:text('id').primaryKey(), name:text('name').notNull(), number:text('number').notNull(), terms:text('terms').notNull().default('[]'), note:text('note').notNull().default('')});
export const terms = sqliteTable('terms', {id:text('id').primaryKey(), name:text('name').notNull(), grade:text('grade').notNull(), active:integer('active').notNull().default(0), archived:integer('archived').notNull().default(0)});
export const posts = sqliteTable('posts', {id:text('id').primaryKey(), owner:text('owner').notNull(), kind:text('kind').notNull(), title:text('title').notNull(), body:text('body').notNull().default(''), term:text('term').notNull(), children:text('children').notNull().default('[]'), visibility:text('visibility').notNull().default('private'), public:integer('public').notNull().default(0), status:text('status').notNull().default('draft'), featured:integer('featured').notNull().default(0), pinned:integer('pinned').notNull().default(0), cover:text('cover'), rejection:text('rejection').notNull().default(''), parent:text('parent'), revision:integer('revision').notNull().default(1), created:text('created').notNull(), updated:text('updated').notNull(), deleted:text('deleted')},t=>[index('idx_posts_status_term').on(t.status,t.term)]);
export const files = sqliteTable('files', {id:text('id').primaryKey(), post:text('post').notNull(), name:text('name').notNull(), mime:text('mime').notNull(), size:integer('size').notNull(), position:integer('position').notNull().default(0), caption:text('caption').notNull().default(''), created:text('created').notNull()},t=>[index('idx_files_post').on(t.post)]);
export const comments = sqliteTable('comments', {id:text('id').primaryKey(), post:text('post'), owner:text('owner').notNull(), name:text('name').notNull(), body:text('body').notNull(), private:integer('private').notNull().default(0), status:text('status').notNull().default('pending'), reply:text('reply').notNull().default(''), created:text('created').notNull()},t=>[index('idx_comments_post').on(t.post)]);
export const invites = sqliteTable('invites', {id:text('id').primaryKey(), email:text('email').notNull(), role:text('role').notNull(), students:text('students').notNull(), expires:text('expires').notNull(), used:text('used')});
export const settings = sqliteTable('settings', {id:text('id').primaryKey(), value:text('value').notNull()});
export const audit = sqliteTable('audit', {id:text('id').primaryKey(), actor:text('actor').notNull(), action:text('action').notNull(), target:text('target').notNull(), created:text('created').notNull()});
export const versions = sqliteTable('versions', {id:text('id').primaryKey(), post:text('post').notNull(), payload:text('payload').notNull(), created:text('created').notNull()},t=>[index('idx_versions_post').on(t.post)]);
export const uploadSessions = sqliteTable('upload_sessions',{id:text('id').primaryKey(),owner:text('owner').notNull(),post:text('post').notNull(),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),fingerprint:text('fingerprint').notNull(),storageId:text('storage_id').notNull(),status:text('status').notNull().default('open'),created:text('created').notNull(),expires:text('expires').notNull()},t=>[index('idx_upload_sessions_owner_post').on(t.owner,t.post)]);
export const uploadParts = sqliteTable('upload_parts',{id:text('id').primaryKey(),session:text('session').notNull(),number:integer('number').notNull(),size:integer('size').notNull(),etag:text('etag').notNull()},t=>[index('idx_upload_parts_session').on(t.session)]);
