import {chromium} from 'file:///C:/Users/sheng/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const errors=[];await mkdir('outputs',{recursive:true});const headers={cookie:'__sites_local_auth=1',origin:'http://127.0.0.1:5173','Content-Type':'application/json'};const checkpoint=await(await fetch('http://127.0.0.1:5173/api/classroom',{method:'POST',headers,body:JSON.stringify({action:'backup'})})).json();
try{const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5173/');await page.waitForFunction(()=>document.querySelectorAll('.content-card').length===3);await page.screenshot({path:'outputs/home-desktop.png',fullPage:true});assert.equal(await page.title(),'银城状元星 · 三年级2班成长空间');
 await context.addCookies([{name:'__sites_local_auth',value:'1',url:'http://127.0.0.1:5173',sameSite:'Lax'}]);await page.reload();await page.getByRole('button',{name:'老师后台'}).click();await page.getByRole('heading',{name:'内容管理',exact:true}).waitFor();await page.screenshot({path:'outputs/admin-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'学生名单',exact:true}).click();await page.locator('input[type=file]').setInputFiles('outputs/名单验证.xlsx');await page.getByRole('heading',{name:'导入预览 · 2人'}).waitFor();await page.getByRole('button',{name:'内容管理',exact:true}).click();await page.getByRole('button',{name:'发布内容',exact:true}).click();await page.getByPlaceholder('给这份成长记录起个名字').fill('界面自动保存验证');await page.getByPlaceholder('写下活动故事、作文正文，或作品背后的想法…').fill('这条草稿用于验证界面自动保存。');await page.getByText('全班共享',{exact:true}).last().click();await page.waitForFunction(()=>document.querySelector('.save-status')?.textContent?.includes('已保存到服务器'));await page.getByRole('button',{name:'保存并关闭'}).click();await page.getByRole('button',{name:'界面自动保存验证',exact:true}).waitFor();
 await page.getByRole('row').filter({has:page.getByRole('button',{name:'界面自动保存验证',exact:true})}).getByRole('button',{name:'编辑',exact:true}).click();await page.getByRole('dialog').locator('input[type=file]').setInputFiles('public/campus.png');await page.getByText('文件已上传并保存',{exact:true}).waitFor();await page.getByRole('button',{name:'保存并关闭'}).click();
 const id=await page.evaluate(async()=>{const d=await(await fetch('/api/classroom')).json();const post=d.posts.find(p=>p.title==='界面自动保存验证');if(!d.files.some(f=>f.post===post.id&&f.name==='campus.png'))throw new Error('上传文件未保存');return post.id});await page.evaluate(async id=>{await fetch('/api/classroom',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'delete',id})})},id);
 await context.clearCookies();await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:5173/');await page.waitForFunction(()=>document.querySelectorAll('.content-card').length===3);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'outputs/home-mobile.png',fullPage:true});
 await context.addCookies([{name:'__sites_local_auth',value:'1',url:'http://127.0.0.1:5173',sameSite:'Lax'},{name:'yc_preview_role',value:'parent',url:'http://127.0.0.1:5173',sameSite:'Lax'}]);await page.reload();await page.getByRole('button',{name:'上传活动照片',exact:true}).click();await page.getByRole('dialog').waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'outputs/editor-mobile.png',fullPage:false});await page.getByRole('button',{name:'保存并关闭'}).click();await page.screenshot({path:'outputs/parent-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);await writeFile('outputs/ui-verification.json',JSON.stringify({passed:['桌面公开首页','老师后台','编辑自动保存','390px手机无横向溢出','手机家长投稿表单'],errors},null,2));console.log('PASS 桌面、手机、后台、自动保存与投稿表单；无浏览器运行错误');
}finally{if(checkpoint.key)await fetch('http://127.0.0.1:5173/api/classroom',{method:'POST',headers,body:JSON.stringify({action:'restoreBackup',key:checkpoint.key})});await browser.close()}
