import { cookies } from 'next/headers';
import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '../../chatgpt-auth';
import { all,one,run,id,now,member,mustMember,teacher,visible,parse,log,snapshot,bucket,database,checkOrigin,AccessError,defaultSettings,defaultTerm,examples,type Post,type Member } from '../../../lib/classroom';
export const dynamic='force-dynamic';
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
function fail(e:unknown){if(e instanceof AccessError)return response({error:e.message},e.status);console.error('classroom',e);return response({error:'暂时无法完成操作，内容没有丢失，请稍后重试。'},503)}
async function setting(key:string,fallback:unknown){const s=await one<{value:string}>('SELECT value FROM settings WHERE id=?',key);return s?JSON.parse(s.value):fallback;}
export async function GET(req:Request){try{const m=await member();const url=new URL(req.url);if(url.searchParams.get('export')){if(m?.role!=='admin')throw new AccessError('无权导出',403);const b=await snapshot(m);const obj=await bucket().get(b.key);return new Response(obj!.body,{headers:{'Content-Type':'application/json','Content-Disposition':'attachment; filename="yincheng-backup.json"','Cache-Control':'no-store'}})}
 let posts=await all<Post>('SELECT * FROM posts ORDER BY pinned DESC,created DESC');const empty=posts.length===0; if(empty)posts=examples();
 const filtered=posts.filter(p=>visible(p,m));const students=await all<{id:string;name:string;number:string;terms:string;note:string}>('SELECT * FROM students ORDER BY number');const safeStudents=m?students.map(s=>({...s,note:teacher(m)||parse(m.students).includes(s.id)?s.note:''})):[];
 const postIds=new Set(filtered.map(p=>p.id));const fs=(await all('SELECT * FROM files ORDER BY position,created')).filter(f=>postIds.has(String(f.post)));
 const cs=m?(await all('SELECT * FROM comments ORDER BY created DESC')).filter(c=>teacher(m)||c.owner===m.id||(!c.private&&c.status==='approved'&&postIds.has(String(c.post)))):[];
 const terms=await all('SELECT * FROM terms ORDER BY id DESC');
 return response({pendingUploads:m?await all("SELECT id,post,name,size,expires FROM upload_sessions WHERE owner=? AND status=? AND expires>?",m.id,"open",now()):[],member:m,authenticated:!!(await getChatGPTUser()),local:import.meta.env.DEV,posts:filtered,files:fs,students:safeStudents,terms:terms.length?terms:[defaultTerm],settings:await setting('site',defaultSettings),example:empty,comments:cs,accounts:m?.role==='admin'?await all('SELECT * FROM members'):[],audit:teacher(m)?await all('SELECT * FROM audit ORDER BY created DESC LIMIT 80'):[],versions:teacher(m)?await all('SELECT id,post,created FROM versions ORDER BY created DESC LIMIT 100'):[],recycle:teacher(m)?posts.filter(p=>p.deleted):[],lastBackup:m?.role==='admin'?await setting('lastBackup',null):null});
 }catch(e){return fail(e)}}
export async function POST(req:Request){try{checkOrigin(req);const b=await req.json() as Record<string,any>;const action=b.action;
 if(action==='preview'){if(!import.meta.env.DEV)throw new AccessError('不可用',404);if(!(await getChatGPTUser()))throw new AccessError('请先登录',401);(await cookies()).set('yc_preview_role',b.role==='parent'?'parent':'admin',{httpOnly:true,sameSite:'strict',path:'/'});return response({ok:true});}
 if(action==='join'){const u=await getChatGPTUser();if(!u)throw new AccessError('请先登录',401);const invitation=await one<any>('SELECT * FROM invites WHERE id=?',String(b.code));if(!invitation||invitation.used||invitation.expires<now()||invitation.email.toLowerCase()!==u.email.toLowerCase())throw new AccessError('邀请无效、已使用、已过期或邮箱不匹配');if(await one('SELECT id FROM members WHERE id=?',u.userId))throw new AccessError('你已经加入班级');await database().batch([database().prepare('INSERT INTO members(id,email,name,role,students) VALUES(?,?,?,?,?)').bind(u.userId,u.email,u.displayName,invitation.role,invitation.students),database().prepare('UPDATE invites SET used=? WHERE id=? AND used IS NULL').bind(u.userId,invitation.id)]);return response({ok:true});}
 if(action==='activate'){const u=await getChatGPTUser();if(!u)throw new AccessError('请先登录',401);const secret=(env as unknown as Record<string,string>).ADMIN_SETUP_KEY;if(!secret||secret.length<24||b.code!==secret)throw new AccessError('管理员启用码不正确',403);await run('INSERT INTO members(id,email,name,role,students) SELECT ?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM members WHERE role=?)',u.userId,u.email,u.displayName,'admin','[]','admin');return response({ok:true});}
 const m=await mustMember();const needTeacher=()=>{if(!teacher(m))throw new AccessError('仅老师可操作',403)};const needAdmin=()=>{if(m.role!=='admin')throw new AccessError('仅管理员可操作',403)};
 if(action==='seed'){needAdmin();if(await one('SELECT id FROM posts LIMIT 1'))throw new AccessError('已有内容，不能重复初始化');const statements=examples().map(p=>database().prepare('INSERT INTO posts(id,owner,kind,title,body,term,children,visibility,public,status,featured,pinned,cover,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(p.id,m.id,p.kind,p.title,p.body,p.term,p.children,p.visibility,p.public,p.status,p.featured,p.pinned,p.cover,p.created,p.updated));statements.push(database().prepare('INSERT INTO terms(id,name,grade,active,archived) VALUES(?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(defaultTerm.id,defaultTerm.name,defaultTerm.grade,1,0));for(const [sid,name,num] of [['s1','星小禾','01'],['s2','星小川','02'],['s3','星小满','03'],['s4','星小宁','04']])statements.push(database().prepare('INSERT INTO students(id,name,number,terms,note) VALUES(?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(sid,name,num,JSON.stringify([defaultTerm.id]),'示例学生，非真实孩子资料。'));await database().batch(statements);await log(m,'初始化示例内容','class');return response({ok:true});}
 if(action==='save'){const old=b.id?await one<Post>('SELECT * FROM posts WHERE id=?',b.id):null;if(old&&!teacher(m)&&old.owner!==m.id)throw new AccessError('无权编辑',403);if(old?.deleted)throw new AccessError('请先恢复回收站内容');const draftKind=String(b.kind||old?.kind||'work');if(!['album','work','article','notice'].includes(draftKind))throw new AccessError('内容类型不正确');if(!teacher(m)&&!['album','work'].includes(draftKind))throw new AccessError('家长只能投稿照片或作品',403);
 const title=String(b.title||'').trim().slice(0,120),body=String(b.body||'').slice(0,50000);const children=Array.isArray(b.children)?b.children.filter((x:unknown)=>typeof x==='string'):[];if(!teacher(m)&&children.some((s:string)=>!parse(m.students).includes(s)))throw new AccessError('只能关联自己的孩子',403);if(children.length){const known=await all<{id:string}>('SELECT id FROM students');if(children.some((s:string)=>!known.some(k=>k.id===s)))throw new AccessError('关联学生不存在');}
 const visibility=b.visibility==='shared'?'shared':'private';if(old&&teacher(m)&&old.owner!==m.id&&old.visibility==='private'&&visibility==='shared'&&!b.authorized)throw new AccessError('扩大投稿范围前，请确认已取得投稿家长同意');const submit=b.submit===true;if(submit&&old&&await one('SELECT id FROM upload_sessions WHERE post=? AND status=? AND expires>? LIMIT 1',old.id,'open',now()))throw new AccessError('有文件尚未完成，请继续上传或放弃未完成的任务后发布');if(submit&&!title)throw new AccessError('请填写标题');if(submit&&visibility==='private'&&!children.length)throw new AccessError('私密内容请关联学生');const term=String(b.term||defaultTerm.id);const t=await one<any>('SELECT * FROM terms WHERE id=?',term);if(!t)throw new AccessError('所属学期不存在，请先初始化班级');if(!teacher(m)&&t.archived)throw new AccessError('该学期已归档，暂不接受投稿');
 let postId=old?.id||id();let parent=old?.parent||null;let revision=(old?.revision||0)+1;const status=submit?(teacher(m)?'published':'pending'):'draft';
 if(old?.status==='published'&&!teacher(m)){const ongoing=await one<Post>('SELECT * FROM posts WHERE parent=? AND owner=? AND status IN (?,?) AND deleted IS NULL',old.id,m.id,'draft','pending');if(ongoing)throw new AccessError('已有修改稿，请在我的投稿中继续编辑');postId=id();parent=old.id;revision=1;}
 else if(old&&typeof b.revision==='number'&&b.revision!==old.revision)throw new AccessError('内容已在其他窗口修改，请重新打开最新版本',409);
 const statements=[];if(old&&postId===old.id)statements.push(database().prepare('INSERT INTO versions(id,post,payload,created) VALUES(?,?,?,?)').bind(id(),old.id,JSON.stringify(old),now()));
 statements.push(database().prepare('INSERT INTO posts(id,owner,kind,title,body,term,children,visibility,public,status,featured,pinned,cover,parent,revision,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,title=excluded.title,body=excluded.body,term=excluded.term,children=excluded.children,visibility=excluded.visibility,status=excluded.status,revision=excluded.revision,updated=excluded.updated,rejection=?, public=CASE WHEN excluded.status=? AND excluded.visibility=? THEN posts.public ELSE 0 END').bind(postId,old?.owner||m.id,draftKind,title,body,term,JSON.stringify(children),visibility,teacher(m)&&visibility==='shared'&&submit?(old?.public||0):0,status,old?.featured||0,old?.pinned||0,old?.cover||null,parent,revision,old?.created||now(),now(),'','published','shared'));
 await database().batch(statements);if(submit)await log(m,teacher(m)?'发布内容':'提交审核',postId);return response({ok:true,id:postId,revision,status});}
 if(action==='review'||action==='delete'||action==='restore'||action==='withdraw'||action==='feature'||action==='public'||action==='cover'){const p=await one<Post>('SELECT * FROM posts WHERE id=?',String(b.id));if(!p)throw new AccessError('内容不存在',404);
 if(action==='withdraw'){if(p.owner!==m.id&&!teacher(m))throw new AccessError('无权撤回',403);await run('UPDATE posts SET status=?,public=0,updated=? WHERE id=?','draft',now(),p.id);}
 else if(action==='delete'){if(p.owner!==m.id&&!teacher(m))throw new AccessError('无权删除',403);await run('UPDATE posts SET deleted=?,public=0 WHERE id=?',now(),p.id);}
 else if(action==='restore'){needTeacher();if(p.deleted&&Date.now()-Date.parse(p.deleted)>30*86400000)throw new AccessError('已超过30天恢复期');await run('UPDATE posts SET deleted=NULL,status=?,public=0 WHERE id=?','draft',p.id);}
 else if(action==='review'){needTeacher();if(p.status!=='pending')throw new AccessError('该内容不在待审核状态');if(!b.approve&&!String(b.reason||'').trim())throw new AccessError('请填写退回原因');const statements=[];if(b.approve&&p.parent){const parent=await one<Post>('SELECT * FROM posts WHERE id=?',p.parent);if(parent){statements.push(database().prepare('INSERT INTO versions(id,post,payload,created) VALUES(?,?,?,?)').bind(id(),p.id,JSON.stringify(parent),now()));statements.push(database().prepare('UPDATE posts SET deleted=?,public=0 WHERE id=?').bind(now(),parent.id));statements.push(database().prepare('UPDATE files SET post=? WHERE post=?').bind(p.id,parent.id));}}
 statements.push(database().prepare('UPDATE posts SET status=?,rejection=?,updated=? WHERE id=?').bind(b.approve?'published':'returned',b.approve?'':String(b.reason).slice(0,1000),now(),p.id));await database().batch(statements);}
 else if(action==='public'){needAdmin();if(p.status!=='published')throw new AccessError('只能公开已发布内容');if(b.enabled&&!b.authorized)throw new AccessError('请确认已获得相关孩子的展示授权');await run('UPDATE posts SET public=?,visibility=CASE WHEN ?=1 THEN ? ELSE visibility END WHERE id=?',b.enabled?1:0,b.enabled?1:0,'shared',p.id);}
 else if(action==='cover'){needTeacher();const file=await one<any>('SELECT id,mime FROM files WHERE id=? AND post=?',b.file,p.id);if(!file||!file.mime.startsWith('image/'))throw new AccessError('请选择本内容中的图片');await run('UPDATE posts SET cover=? WHERE id=?','/api/files/'+file.id,p.id);}
 else {needTeacher();await run('UPDATE posts SET featured=?,pinned=? WHERE id=?',b.featured?1:0,b.pinned?1:0,p.id);}
 await log(m,action,p.id);return response({ok:true});}
 if(action==='fileEdit'){const f=await one<any>('SELECT * FROM files WHERE id=?',b.id);const p=f?await one<Post>('SELECT * FROM posts WHERE id=?',f.post):null;if(!p||p.deleted||(!teacher(m)&&(p.owner!==m.id||p.status==='published')))throw new AccessError('无权调整该文件',403);if(b.direction){const fs=await all<any>('SELECT id FROM files WHERE post=? ORDER BY position,created',p.id);const i=fs.findIndex(x=>x.id===f.id),target=i+(b.direction==='up'?-1:1);if(target>=0&&target<fs.length){[fs[i],fs[target]]=[fs[target],fs[i]];await database().batch(fs.map((x,j)=>database().prepare('UPDATE files SET position=? WHERE id=?').bind(j,x.id)));}}else await run('UPDATE files SET caption=? WHERE id=?',String(b.caption||'').slice(0,500),f.id);await log(m,'调整素材',f.id);return response({ok:true});}
 if(action==='comment'){const body=String(b.body||'').trim().slice(0,3000);if(!body)throw new AccessError('请填写留言');const p=b.post?await one<Post>('SELECT * FROM posts WHERE id=?',b.post):null;if(b.post&&(!p||!visible(p,m)||p.status!=='published'))throw new AccessError('该内容不可留言',403);if(p&&!teacher(m)){const term=await one<any>('SELECT archived FROM terms WHERE id=?',p.term);if(term?.archived)throw new AccessError('历史学期留言已关闭');}await run('INSERT INTO comments(id,post,owner,name,body,private,status,created) VALUES(?,?,?,?,?,?,?,?)',id(),p?.id||null,m.id,m.name,body,!p||b.private?1:0,teacher(m)||!p||b.private?'approved':'pending',now());return response({ok:true});}
 if(action==='reviewComment'){needTeacher();await run('UPDATE comments SET status=?,reply=? WHERE id=?',b.approve?'approved':'rejected',String(b.reply||'').slice(0,3000),b.id);await log(m,'审核或回复留言',b.id);return response({ok:true});}
 if(action==='students'){needTeacher();if(!Array.isArray(b.rows)||!b.rows.length||b.rows.length>200)throw new AccessError('请导入1至200名学生');const duplicate=new Set();const stmts=[];for(const row of b.rows){const name=String(row.name||'').trim(),number=String(row.number||'').trim();if(!name||!number||name.length>40||number.length>20||duplicate.has(number))throw new AccessError('姓名和学号必填，同一批次学号不能重复');duplicate.add(number);const existing=await one<any>('SELECT * FROM students WHERE number=?',number);const assigned=Array.from(new Set([...parse(existing?.terms||'[]'),String(b.term||defaultTerm.id)]));stmts.push(database().prepare('INSERT INTO students(id,name,number,terms,note) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,terms=excluded.terms').bind(existing?.id||id(),name,number,JSON.stringify(assigned),''));}await database().batch(stmts);await log(m,'导入学生名单',String(b.rows.length));return response({ok:true});}
 if(action==='studentNote'){needTeacher();await run('UPDATE students SET note=? WHERE id=?',String(b.note||'').slice(0,5000),b.id);await log(m,'修改私人资料',b.id);return response({ok:true});}
 if(action==='term'){needAdmin();const name=String(b.name||'').trim(),grade=String(b.grade||'').trim();if(!name||!grade)throw new AccessError('请填写学期与年级');const termId=id();await database().batch([database().prepare('UPDATE terms SET active=0,archived=1 WHERE active=1'),database().prepare('INSERT INTO terms(id,name,grade,active,archived) VALUES(?,?,?,?,?)').bind(termId,name,grade,1,0)]);await log(m,'创建新学期',termId);return response({ok:true});}
 if(action==='termArchive'){needAdmin();await run('UPDATE terms SET archived=? WHERE id=?',b.archived?1:0,b.id);await log(m,'调整学期归档',b.id);return response({ok:true});}
 if(action==='invite'){needAdmin();const email=String(b.email||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new AccessError('请填写有效邮箱');const role=b.role==='teacher'?'teacher':'parent';const children=Array.isArray(b.children)?b.children:[];if(role==='parent'&&!children.length)throw new AccessError('请关联孩子');const known=await all<{id:string}>('SELECT id FROM students');if(children.some((s:string)=>!known.some(k=>k.id===s)))throw new AccessError('学生不存在');const code=id()+id();await run('INSERT INTO invites(id,email,role,students,expires) VALUES(?,?,?,?,?)',code,email,role,JSON.stringify(children),new Date(Date.now()+7*86400000).toISOString());await log(m,'创建成员邀请',email);return response({ok:true,code});}
 if(action==='settings'){needAdmin();const value={...defaultSettings,name:String(b.value.name||defaultSettings.name).slice(0,40),className:String(b.value.className||defaultSettings.className).slice(0,40),motto:String(b.value.motto||'').slice(0,100),intro:String(b.value.intro||'').slice(0,1000),contact:String(b.value.contact||'').slice(0,300),modules:Array.isArray(b.value.modules)?b.value.modules.filter((x:string)=>['album','work','article'].includes(x)):defaultSettings.modules,carousel:!!b.value.carousel};await run('INSERT INTO settings(id,value) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value','site',JSON.stringify(value));await log(m,'调整首页','site');return response({ok:true});}
 if(action==='backup'){needAdmin();return response({ok:true,...await snapshot(m)});}
 if(action==='restoreBackup'){needAdmin();let source=b.snapshot;if(b.key){if(!String(b.key).startsWith('backups/'))throw new AccessError('备份路径不正确');const stored=await bucket().get(String(b.key));if(!stored)throw new AccessError('备份不存在');source=JSON.parse(await stored.text());}if(!source||source.format!=='yincheng-stars-v1')throw new AccessError('不是本网站的备份文件');
 const columns:Record<string,string[]>={members:['id','email','name','role','students'],students:['id','name','number','terms','note'],terms:['id','name','grade','active','archived'],posts:['id','owner','kind','title','body','term','children','visibility','public','status','featured','pinned','cover','rejection','parent','revision','created','updated','deleted'],files:['id','post','name','mime','size','position','caption','created'],comments:['id','post','owner','name','body','private','status','reply','created'],invites:['id','email','role','students','expires','used'],settings:['id','value'],audit:['id','actor','action','target','created'],versions:['id','post','payload','created']};
 let count=0;for(const t of Object.keys(columns)){if(!Array.isArray(source[t]))throw new AccessError('备份缺少数据表：'+t);count+=source[t].length;for(const row of source[t]){if(!row||typeof row.id!=='string'||columns[t].some(k=>row[k]!==null&&!['string','number'].includes(typeof row[k])))throw new AccessError('备份记录不完整：'+t);}}if(count>1500)throw new AccessError('当前在线恢复支持1500条记录以内，较大备份请联系管理员处理');if(!import.meta.env.DEV&&!source.members.some((x:Member)=>x.id===m.id&&x.role==='admin'))throw new AccessError('备份不包含你的管理员账号，不能直接恢复');
 for(const f of source.files){if(!await bucket().head('uploads/'+f.id))throw new AccessError('备份中的文件已不在当前存储中，无法完整恢复');}const before=await snapshot(m);const stmts=[];for(const t of Object.keys(columns))stmts.push(database().prepare('DELETE FROM '+t));for(const [t,cols] of Object.entries(columns))for(const row of source[t])stmts.push(database().prepare('INSERT INTO '+t+'('+cols.join(',')+') VALUES('+cols.map(()=>'?').join(',')+')').bind(...cols.map(k=>row[k])));await database().batch(stmts);await log(m,'恢复数据备份',before.key);return response({ok:true,safetyBackup:before.key});}
 if(action==='restoreVersion'){needTeacher();const v=await one<any>('SELECT * FROM versions WHERE id=?',b.id);if(!v)throw new AccessError('版本不存在');const p=JSON.parse(v.payload);const current=await one<Post>('SELECT * FROM posts WHERE id=?',v.post);if(!current)throw new AccessError('内容不存在');await database().batch([database().prepare('INSERT INTO versions(id,post,payload,created) VALUES(?,?,?,?)').bind(id(),current.id,JSON.stringify(current),now()),database().prepare('UPDATE posts SET title=?,body=?,status=?,public=0,revision=revision+1,updated=? WHERE id=?').bind(p.title,p.body,'draft',now(),v.post)]);await log(m,'恢复历史正文',v.post);return response({ok:true});}
 throw new AccessError('未知操作');
 }catch(e){return fail(e)}}
